server:
  port: 8384
# Oracle Connect
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@127.0.0.1:1521:xe
    username: scottJpa
    password: tiger
     
  #Jpa Setting
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update